apiVersion: batch/v1
kind: CronJob
metadata:
  name: msynbot.unconnected-pages
  labels:
    name: msynbot.unconnected-pages
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  schedule: "42 2 * * 6"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            toolforge: tool
        spec:
          containers:
          - name: itemstats
            image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
            command: [ "/data/project/msynbot/pywikibot_tasks/unconnected_pages/venv/bin/python3" ]
            args: [ "/data/project/shared/pywikibot/stable/pwb.py", "/data/project/msynbot/pywikibot_tasks/unconnected_pages/unconnected_pages.py" ]
            workingDir: /data/project/msynbot/pywikibot_tasks/unconnected_pages
            env:
            - name: HOME
              value: /data/project/msynbot
          restartPolicy: OnFailure
